services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${TRAVELMATE_DATABASE_USER}
      POSTGRES_DB: ${TRAVELMATE_DATABASE_NAME}
      POSTGRES_PASSWORD: ${TRAVELMATE_DATABASE_PASSWORD}
    volumes:
     -  db:/var/lib/postgresql/data

  app:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    environment:
      TRAVELMATE_DATABASE_HOST: ${TRAVELMATE_DATABASE_HOST}
      TRAVELMATE_DATABASE_NAME: ${TRAVELMATE_DATABASE_NAME}
      TRAVELMATE_DATABASE_USER: ${TRAVELMATE_DATABASE_USER}
      TRAVELMATE_DATABASE_PORT: ${TRAVELMATE_DATABASE_PORT:-5432}
      TRAVELMATE_DATABASE_PASSWORD: ${TRAVELMATE_DATABASE_PASSWORD:-db}
    depends_on:
      - db

volumes:
  db:
    driver: local
